options:
  logging: CLOUD_LOGGING_ONLY

steps:

- id: Docker build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}', '.']
  
- id: Container image push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}']

- id: Cloud run deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}'
  - '--port'
  - '3001'
  - '--memory=1Gi'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--service-account'
  - '${_SERVICE_ACCOUNT}'
  - '--max-instances'
  - '5'
  - '--timeout'
  - '900'


images:
- ${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}

substitutions:
  _REPO_REGION: asia-south1-docker.pkg.dev
  _REPO_NAME: prox-api-1842
  _SERVICE_NAME: prox-api-1842
  _REGION: asia-south1
  _PROJ_ID: prox-api-1842
  _SERVICE_ACCOUNT: 748942250889-compute@developer.gserviceaccount.com
